// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {structs} from '../models';

export function GetEnvs():Promise<Array<structs.Stages>>;

export function Greet(arg1:string):Promise<string>;

export function IsStagePresent(arg1:string):Promise<boolean>;

export function ReadCipherFile(arg1:string,arg2:string):Promise<string>;

export function WriteCipherFile(arg1:string,arg2:string,arg3:string):Promise<string>;
