// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnvs() {
  return window['go']['ui']['App']['GetEnvs']();
}

export function IsStagePresent(arg1) {
  return window['go']['ui']['App']['IsStagePresent'](arg1);
}

export function ReadCipherFile(arg1, arg2) {
  return window['go']['ui']['App']['ReadCipherFile'](arg1, arg2);
}

export function WriteCipherFile(arg1, arg2, arg3) {
  return window['go']['ui']['App']['WriteCipherFile'](arg1, arg2, arg3);
}
